name: newstation
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - torch
    - pytorch-lightning
    - transformers
    - flair
    - streamlit
    - scikit-learn
    - ipykernel
    - beautifulsoup4
    - jaro-winkler==2.0.3
    - sacremoses